// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWsTlgOUudfC3yr-w7LTU4tolEqdqqWDc',
    appId: '1:951105836363:android:155f9aad2b722d760544ce',
    messagingSenderId: '951105836363',
    projectId: 'chat-app-317a5',
    storageBucket: 'chat-app-317a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATximNstgtVnA2eLGdBVucK7iMG3AgyA4',
    appId: '1:951105836363:ios:f921ae28870b8c450544ce',
    messagingSenderId: '951105836363',
    projectId: 'chat-app-317a5',
    storageBucket: 'chat-app-317a5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5TMkHbEIL65sTs80ofZ8UsANs4I8qa98',
    appId: '1:951105836363:web:4cbdd95f774d05ee0544ce',
    messagingSenderId: '951105836363',
    projectId: 'chat-app-317a5',
    authDomain: 'chat-app-317a5.firebaseapp.com',
    storageBucket: 'chat-app-317a5.appspot.com',
  );

}